# Generated by Django 3.0.4 on 2020-04-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geocode',
            old_name='free_request',
            new_name='request_count',
        ),
    ]
